name: Publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      - run:
          working-directory: gatsby-theme-minimalism
          shell: yarn install && yarn publish
          env:
            NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}